### ISSUE TITLE
Using DOMContentLoaded with enhance

### ISSUE THREAD

**Issue by fatpixelstudio** [filamentgroup/enhance#6]
When using enhance to asynchronously load my javascript, I sometimes notice issues when using `DOMContentLoaded`.

My javascript is in one file, no jquery, just plain-old-JS. At the bottom of the file something like this:

``` javascript
document.addEventListener('DOMContentLoaded', function() {
    console.log('DOM is loaded');
    site.init();
   eventhandlers.set();
});
```

The 'DOM is loaded' log is now shown only 50% of the time when i refresh the page. It appears the script is loaded before the DOM is even available, or something?

Any ideas on what's going on and how to fix this?

**Comment by mrmartineau** [comment]
I recently came across this issue myself and resorted to using `document.onreadystatechange` and checking `document.readyState`. See below for an example:

```js
document.onreadystatechange = function() {
	if (document.readyState == 'interactive' || document.readyState == 'complete') {
		// your dom ready code goes here
	}
}
```

More information can be found on MDN:
* https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange
* https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

**Comment by fatpixelstudio** [comment]
Thanks @mrmartineau ! That's a nice solution and a useful resource.

We resorted to using this domready script: https://github.com/ded/domready which also works fine.

Hope this might help someone in the future.
